<?php

namespace Database\Seeders;

use App\Models\PrintCategory;
use App\Models\PrintItem;
use Illuminate\Database\Seeder;

class PrintItemSeeder extends Seeder
{
    public function run(): void
    {
        $categoryMap = PrintCategory::pluck('id', 'code')->toArray();

        $items = [
            // --- PAPER & STOCK CATEGORY ITEMS ---
            [
                'name' => '70gsm Premium Bond Paper Reams',
                'item_code' => 'STK-BOND-0001',
                'category_id' => $categoryMap['STOCK'] ?? null,
                'description' => 'High-whiteness multipurpose bond paper for daily document printing and high-speed copying.',
                'paper_type' => 'Bond Paper (70gsm)',
                'paper_size' => 'A4 (8.27 x 11.69 in)',
                'brand' => 'Advance Premium',
                'model' => 'AP-70A4',
                'print_sides' => 'double_sided',
                'color_mode' => 'monochrome',
                'turnaround_time' => 'In Stock',
                'base_price' => 220.00,
                'available_quantity' => 150,
                'unit' => 'reams',
                'compatibility' => 'Compatible with all Laser & Inkjet printers',
                'min_quantity' => 1,
                'status' => 'active',
                'notes' => '500 sheets per ream. Jam-free guaranteed stock.',
                'sort_order' => 1,
            ],
            [
                'name' => '260gsm High-Gloss Archival Photo Paper',
                'item_code' => 'STK-PHTO-0002',
                'category_id' => $categoryMap['STOCK'] ?? null,
                'description' => 'Heavyweight resin-coated glossy photo paper for vibrant portrait and studio prints.',
                'paper_type' => 'Glossy Photo Paper (260gsm)',
                'paper_size' => '4R / A4 Packs',
                'brand' => 'Epson Original',
                'model' => 'S041286',
                'print_sides' => 'single_sided',
                'color_mode' => 'full_color',
                'turnaround_time' => 'In Stock',
                'base_price' => 450.00,
                'available_quantity' => 85,
                'unit' => 'packs',
                'compatibility' => 'Epson EcoTank, SureColor & Canon PIXMA Photo Printers',
                'min_quantity' => 1,
                'status' => 'active',
                'notes' => '100 sheets per pack. Instant dry resin-coated finish.',
                'sort_order' => 2,
            ],
            [
                'name' => '350gsm Heavyweight Matte White Cardstock',
                'item_code' => 'STK-CARD-0003',
                'category_id' => $categoryMap['STOCK'] ?? null,
                'description' => 'Ultra-thick smooth cardstock suitable for business cards, post cards, and covers.',
                'paper_type' => 'Heavy Cardstock (350gsm)',
                'paper_size' => 'SRA3 (12 x 18 in)',
                'brand' => 'Neenah Paper',
                'model' => 'NP-350SRA3',
                'print_sides' => 'variable',
                'color_mode' => 'full_color',
                'turnaround_time' => 'In Stock',
                'base_price' => 680.00,
                'available_quantity' => 40,
                'unit' => 'packs',
                'compatibility' => 'Production Digital Presses (Xerox, Konica Minolta)',
                'min_quantity' => 1,
                'status' => 'active',
                'notes' => '250 sheets per pack.',
                'sort_order' => 3,
            ],
            [
                'name' => '230gsm Parchment Linen Specialty Paper',
                'item_code' => 'STK-SPEC-0004',
                'category_id' => $categoryMap['STOCK'] ?? null,
                'description' => 'Textured linen specialty paper for certificates, diplomas, and formal invitations.',
                'paper_type' => 'Specialty Linen Paper (230gsm)',
                'paper_size' => 'A4 (8.27 x 11.69 in)',
                'brand' => 'Conquest Fine Paper',
                'model' => 'CQ-LIN230',
                'print_sides' => 'single_sided',
                'color_mode' => 'full_color',
                'turnaround_time' => 'In Stock',
                'base_price' => 350.00,
                'available_quantity' => 30,
                'unit' => 'packs',
                'compatibility' => 'High-resolution Inkjet & Laser printers',
                'min_quantity' => 1,
                'status' => 'active',
                'notes' => '100 sheets per pack.',
                'sort_order' => 4,
            ],
            [
                'name' => 'Waterproof Glossy Vinyl Sticker Roll',
                'item_code' => 'STK-VNYL-0005',
                'category_id' => $categoryMap['STOCK'] ?? null,
                'description' => 'Weatherproof self-adhesive glossy vinyl media for large format sticker printing.',
                'paper_type' => 'Adhesive Vinyl Stock',
                'paper_size' => '1.27m x 50m Roll',
                'brand' => 'Orajet',
                'model' => '3164G',
                'print_sides' => 'single_sided',
                'color_mode' => 'full_color',
                'turnaround_time' => 'In Stock',
                'base_price' => 4200.00,
                'available_quantity' => 12,
                'unit' => 'rolls',
                'compatibility' => 'Eco-Solvent, Latex & UV Wide-Format Printers',
                'min_quantity' => 1,
                'status' => 'active',
                'notes' => 'Outdoor durability up to 4 years.',
                'sort_order' => 5,
            ],

            // --- EQUIPMENT & INKS CATEGORY ITEMS ---
            [
                'name' => 'Epson EcoTank L3210 All-in-One Inkjet Printer',
                'item_code' => 'EQP-PRNT-0001',
                'category_id' => $categoryMap['EQUIPMENT'] ?? null,
                'description' => 'High-performance refillable tank printer for high-volume document and photo printing.',
                'paper_type' => 'Multi-stock (Bond, Photo, Glossy)',
                'paper_size' => 'Up to Legal (8.5 x 14 in)',
                'brand' => 'Epson',
                'model' => 'EcoTank L3210',
                'print_sides' => 'variable',
                'color_mode' => 'full_color',
                'turnaround_time' => 'In Service',
                'base_price' => 8990.00,
                'available_quantity' => 4,
                'unit' => 'units',
                'compatibility' => 'Epson 003 Genuine Ink Bottles (C, M, Y, K)',
                'min_quantity' => 1,
                'status' => 'active',
                'notes' => 'Includes 1 set of starter inks. Print speed up to 33 ppm.',
                'sort_order' => 6,
            ],
            [
                'name' => 'HP 85A Black LaserJet Toner Cartridge',
                'item_code' => 'EQP-INK-0002',
                'category_id' => $categoryMap['EQUIPMENT'] ?? null,
                'description' => 'Original HP monochrome laser toner cartridge producing sharp black text.',
                'paper_type' => 'Laser Compatible Stock',
                'paper_size' => 'Standard',
                'brand' => 'HP',
                'model' => 'CE285A (HP 85A)',
                'print_sides' => 'single_sided',
                'color_mode' => 'monochrome',
                'turnaround_time' => 'In Stock',
                'base_price' => 1450.00,
                'available_quantity' => 24,
                'unit' => 'cartridges',
                'compatibility' => 'HP LaserJet Pro P1102 / P1102w / M1212nf MFP',
                'min_quantity' => 1,
                'status' => 'active',
                'notes' => 'Yields approx 1,600 standard pages at 5% coverage.',
                'sort_order' => 7,
            ],
            [
                'name' => 'Canon GI-790 High Yield CMYK Refill Ink Set',
                'item_code' => 'EQP-INK-0003',
                'category_id' => $categoryMap['EQUIPMENT'] ?? null,
                'description' => '4-color high capacity original dye refill ink bottles for Canon G-series printers.',
                'paper_type' => 'Inkjet Paper Stock',
                'paper_size' => 'N/A',
                'brand' => 'Canon',
                'model' => 'GI-790 (BK/C/M/Y)',
                'print_sides' => 'single_sided',
                'color_mode' => 'full_color',
                'turnaround_time' => 'In Stock',
                'base_price' => 1250.00,
                'available_quantity' => 35,
                'unit' => 'sets',
                'compatibility' => 'Canon PIXMA G1010 / G2010 / G3010 / G4010',
                'min_quantity' => 1,
                'status' => 'active',
                'notes' => '70ml per bottle. Black page yield up to 6,000 pages.',
                'sort_order' => 8,
            ],
            [
                'name' => 'Dahle 552 Professional A3 Rotary Trimmer',
                'item_code' => 'EQP-TOOL-0004',
                'category_id' => $categoryMap['EQUIPMENT'] ?? null,
                'description' => 'Heavy-duty rotary paper cutter for precision edge finishing on paper and cardstock.',
                'paper_type' => 'All Paper & Cardstock',
                'paper_size' => 'A3 Cut Length (20 in / 510mm)',
                'brand' => 'Dahle',
                'model' => '552 Professional',
                'print_sides' => 'variable',
                'color_mode' => 'full_color',
                'turnaround_time' => 'In Service',
                'base_price' => 5400.00,
                'available_quantity' => 3,
                'unit' => 'units',
                'compatibility' => 'Cuts up to 20 sheets of 70gsm paper at once',
                'min_quantity' => 1,
                'status' => 'active',
                'notes' => 'Self-sharpening circular blade with automatic clamping.',
                'sort_order' => 9,
            ],
            [
                'name' => 'Fellowes Saturn 3i A3 Heavy-Duty Thermal Laminator',
                'item_code' => 'EQP-TOOL-0005',
                'category_id' => $categoryMap['EQUIPMENT'] ?? null,
                'description' => 'Fast warm-up dual temperature laminating machine for documents, photos, and menus.',
                'paper_type' => 'Lamination Pouches',
                'paper_size' => 'Up to A3 Width',
                'brand' => 'Fellowes',
                'model' => 'Saturn 3i A3',
                'print_sides' => 'double_sided',
                'color_mode' => 'full_color',
                'turnaround_time' => 'In Service',
                'base_price' => 4950.00,
                'available_quantity' => 5,
                'unit' => 'units',
                'compatibility' => 'Accepts 80 to 125 micron hot and cold pouches',
                'min_quantity' => 1,
                'status' => 'active',
                'notes' => '1-minute InstaHeat technology with auto shut-off.',
                'sort_order' => 10,
            ],
            // 1. Documents
            [
                'name' => 'Standard Document Printing',
                'item_code' => 'PRT-DOCS-0001',
                'category_id' => $categoryMap['DOCS'] ?? null,
                'description' => 'Black & white or color document printing for contracts, agreements, and office documents.',
                'paper_type' => '70gsm Premium Bond Paper',
                'paper_size' => 'A4 (8.27 x 11.69 in)',
                'print_sides' => 'double_sided',
                'color_mode' => 'monochrome',
                'turnaround_time' => 'Same Day Express',
                'base_price' => 3.50,
                'min_quantity' => 1,
                'status' => 'active',
                'notes' => 'Stapling and hole-punching options available upon request.',
                'sort_order' => 1,
            ],
            // 2. Pictures/photos
            [
                'name' => 'High-Gloss Photo Prints',
                'item_code' => 'PRT-PHOTO-0002',
                'category_id' => $categoryMap['PHOTO'] ?? null,
                'description' => 'Vibrant, high-resolution photo prints on archival glossy paper for portraits and albums.',
                'paper_type' => '260gsm Premium Archival Glossy Photo Paper',
                'paper_size' => '4R (4 x 6 in)',
                'print_sides' => 'single_sided',
                'color_mode' => 'full_color',
                'turnaround_time' => 'Same Day Express',
                'base_price' => 15.00,
                'min_quantity' => 5,
                'status' => 'active',
                'notes' => 'UV protective coating prevents fading for up to 50 years.',
                'sort_order' => 2,
            ],
            // 3. Posters
            [
                'name' => 'Large Format Display Posters',
                'item_code' => 'PRT-MKTG-0003',
                'category_id' => $categoryMap['MKTG'] ?? null,
                'description' => 'Eye-catching event and promotional posters printed on heavy satin poster stock.',
                'paper_type' => '220gsm Matte Satin Poster Paper',
                'paper_size' => 'A2 (16.5 x 23.4 in)',
                'print_sides' => 'single_sided',
                'color_mode' => 'full_color',
                'turnaround_time' => '1-2 Business Days',
                'base_price' => 180.00,
                'min_quantity' => 1,
                'status' => 'active',
                'notes' => 'Optional foam board mounting or lamination available.',
                'sort_order' => 3,
            ],
            // 4. Flyers
            [
                'name' => 'Promotional Marketing Flyers',
                'item_code' => 'PRT-MKTG-0004',
                'category_id' => $categoryMap['MKTG'] ?? null,
                'description' => 'Bulk marketing flyers for campaigns, product launches, and store openings.',
                'paper_type' => '150gsm Glossy Art Paper',
                'paper_size' => 'A5 (5.83 x 8.27 in)',
                'print_sides' => 'double_sided',
                'color_mode' => 'full_color',
                'turnaround_time' => '1-2 Business Days',
                'base_price' => 4.50,
                'min_quantity' => 100,
                'status' => 'active',
                'notes' => 'Ideal for street distribution and direct mail flyers.',
                'sort_order' => 4,
            ],
            // 5. Brochures
            [
                'name' => 'Tri-Fold Corporate Brochures',
                'item_code' => 'PRT-MKTG-0005',
                'category_id' => $categoryMap['MKTG'] ?? null,
                'description' => 'Full-color folded brochures featuring company overviews, services, and product catalogs.',
                'paper_type' => '200gsm Glossy C2S Art Card',
                'paper_size' => 'Letter Folded Tri-Fold (8.5 x 11 in unfolded)',
                'print_sides' => 'double_sided',
                'color_mode' => 'full_color',
                'turnaround_time' => '2-3 Business Days',
                'base_price' => 12.00,
                'min_quantity' => 50,
                'status' => 'active',
                'notes' => 'Precision scored and folded machine finish.',
                'sort_order' => 5,
            ],
            // 6. Business cards
            [
                'name' => 'Premium Executive Business Cards',
                'item_code' => 'PRT-STAT-0006',
                'category_id' => $categoryMap['STAT'] ?? null,
                'description' => 'Professional business cards with matte lamination and optional spot UV finish.',
                'paper_type' => '350gsm Heavy Matte Smooth Cardstock',
                'paper_size' => 'Standard (3.5 x 2 in)',
                'print_sides' => 'double_sided',
                'color_mode' => 'full_color',
                'turnaround_time' => '1-2 Business Days',
                'base_price' => 350.00,
                'min_quantity' => 100,
                'status' => 'active',
                'notes' => 'Price listed is per box of 100 cards with matte lamination.',
                'sort_order' => 6,
            ],
            // 7. Invitations
            [
                'name' => 'Wedding & Event Invitations',
                'item_code' => 'PRT-STAT-0007',
                'category_id' => $categoryMap['STAT'] ?? null,
                'description' => 'Elegant invitation cards for weddings, galas, birthdays, and corporate events.',
                'paper_type' => '300gsm Textured Pearlized Metallic Stock',
                'paper_size' => '5 x 7 in',
                'print_sides' => 'double_sided',
                'color_mode' => 'full_color',
                'turnaround_time' => '3-5 Business Days',
                'base_price' => 45.00,
                'min_quantity' => 30,
                'status' => 'active',
                'notes' => 'Includes matching envelope and custom gold foil options.',
                'sort_order' => 7,
            ],
            // 8. Receipts
            [
                'name' => 'Official Carbonless Receipt Books',
                'item_code' => 'PRT-STAT-0008',
                'category_id' => $categoryMap['STAT'] ?? null,
                'description' => 'Custom 2-part or 3-part duplicate NCR receipt pads for business transactions.',
                'paper_type' => '55gsm NCR Carbonless Paper (White/Canary)',
                'paper_size' => 'Half Letter (5.5 x 8.5 in)',
                'print_sides' => 'single_sided',
                'color_mode' => 'monochrome',
                'turnaround_time' => '3-5 Business Days',
                'base_price' => 250.00,
                'min_quantity' => 10,
                'status' => 'active',
                'notes' => 'Sequential red numbering included on each booklet (50 sets per book).',
                'sort_order' => 8,
            ],
            // 9. Certificates
            [
                'name' => 'Achievement & Appreciation Certificates',
                'item_code' => 'PRT-STAT-0009',
                'category_id' => $categoryMap['STAT'] ?? null,
                'description' => 'Official certificates for training completion, academic awards, and employee honors.',
                'paper_type' => '230gsm Parchment Linen Specialty Paper',
                'paper_size' => 'A4 (8.27 x 11.69 in)',
                'print_sides' => 'single_sided',
                'color_mode' => 'full_color',
                'turnaround_time' => '1-2 Business Days',
                'base_price' => 30.00,
                'min_quantity' => 10,
                'status' => 'active',
                'notes' => 'Gold foil border stamping available upon request.',
                'sort_order' => 9,
            ],
            // 10. Labels
            [
                'name' => 'Custom Product & Jar Labels',
                'item_code' => 'PRT-LABEL-0010',
                'category_id' => $categoryMap['LABEL'] ?? null,
                'description' => 'Waterproof product packaging labels for cosmetics, food jars, and retail products.',
                'paper_type' => 'Waterproof Glossy Vinyl Label Adhesive',
                'paper_size' => 'Custom Cut Sheet / Roll',
                'print_sides' => 'single_sided',
                'color_mode' => 'full_color',
                'turnaround_time' => '2-3 Business Days',
                'base_price' => 8.00,
                'min_quantity' => 50,
                'status' => 'active',
                'notes' => 'Oil-resistant and scratch-proof lamination.',
                'sort_order' => 10,
            ],
            // 11. Stickers
            [
                'name' => 'Die-Cut Logo Stickers',
                'item_code' => 'PRT-LABEL-0011',
                'category_id' => $categoryMap['LABEL'] ?? null,
                'description' => 'Individual die-cut vinyl stickers for branding, laptop decals, and merchandising.',
                'paper_type' => 'Premium Outdoor Laminated Vinyl',
                'paper_size' => '3 x 3 in (Custom Shape)',
                'print_sides' => 'single_sided',
                'color_mode' => 'full_color',
                'turnaround_time' => '2-3 Business Days',
                'base_price' => 12.50,
                'min_quantity' => 50,
                'status' => 'active',
                'notes' => 'Weatherproof vinyl suitable for outdoor application.',
                'sort_order' => 11,
            ],
            // 12. Books
            [
                'name' => 'Perfect Bound Softcover Books',
                'item_code' => 'PRT-PUB-0012',
                'category_id' => $categoryMap['PUB'] ?? null,
                'description' => 'Professional softcover books, manuals, and novels with glue-bound spine.',
                'paper_type' => '80gsm Cream Book Paper Interior / 300gsm C1S Cover',
                'paper_size' => 'Trade Size (6 x 9 in)',
                'print_sides' => 'double_sided',
                'color_mode' => 'monochrome',
                'turnaround_time' => '5-7 Business Days',
                'base_price' => 220.00,
                'min_quantity' => 20,
                'status' => 'active',
                'notes' => 'Matte or glossy laminated cover finish included.',
                'sort_order' => 12,
            ],
            // 13. Magazines
            [
                'name' => 'Saddle-Stitched Glossy Magazines',
                'item_code' => 'PRT-PUB-0013',
                'category_id' => $categoryMap['PUB'] ?? null,
                'description' => 'Full-color magazines, lookbooks, and corporate newsletters bound with staple spine.',
                'paper_type' => '128gsm Glossy Art Paper Pages / 250gsm Cover',
                'paper_size' => 'A4 (8.27 x 11.69 in)',
                'print_sides' => 'double_sided',
                'color_mode' => 'full_color',
                'turnaround_time' => '3-5 Business Days',
                'base_price' => 95.00,
                'min_quantity' => 25,
                'status' => 'active',
                'notes' => 'Available in 16, 24, 32, or 48 page signatures.',
                'sort_order' => 13,
            ],
            // 14. Newspapers
            [
                'name' => 'Tabloid Newsprint Publications',
                'item_code' => 'PRT-PUB-0014',
                'category_id' => $categoryMap['PUB'] ?? null,
                'description' => 'Authentic newsprint printing for school papers, community news, and vintage style prints.',
                'paper_type' => '45gsm Standard Newsprint Stock',
                'paper_size' => 'Tabloid (11 x 17 in Folded)',
                'print_sides' => 'double_sided',
                'color_mode' => 'full_color',
                'turnaround_time' => '3-5 Business Days',
                'base_price' => 18.00,
                'min_quantity' => 100,
                'status' => 'active',
                'notes' => 'Traditional web press look and feel.',
                'sort_order' => 14,
            ],
            // 15. Calendars
            [
                'name' => 'Custom Spiral Wall & Desk Calendars',
                'item_code' => 'PRT-PUB-0015',
                'category_id' => $categoryMap['PUB'] ?? null,
                'description' => '12-month custom calendars with wire-o binding and thumb cut hanger.',
                'paper_type' => '200gsm Heavy Gloss Art Stock',
                'paper_size' => 'A3 Wall Calendar (11.7 x 16.5 in)',
                'print_sides' => 'double_sided',
                'color_mode' => 'full_color',
                'turnaround_time' => '3-5 Business Days',
                'base_price' => 150.00,
                'min_quantity' => 10,
                'status' => 'active',
                'notes' => 'Includes 12 monthly pages plus front and back cover.',
                'sort_order' => 15,
            ],
            // 16. Resumes/CVs
            [
                'name' => 'Executive Resume & CV Prints',
                'item_code' => 'PRT-DOCS-0016',
                'category_id' => $categoryMap['DOCS'] ?? null,
                'description' => 'High-impact professional resume printing on premium heavyweight linen bond paper.',
                'paper_type' => '100gsm Premium Linen Resume Stock',
                'paper_size' => 'A4 / US Letter',
                'print_sides' => 'single_sided',
                'color_mode' => 'full_color',
                'turnaround_time' => 'Same Day Express',
                'base_price' => 8.00,
                'min_quantity' => 5,
                'status' => 'active',
                'notes' => 'Includes crisp monochrome text output and crisp logo header.',
                'sort_order' => 16,
            ],
            // 17. Reports
            [
                'name' => 'Comb-Bound Annual & Financial Reports',
                'item_code' => 'PRT-DOCS-0017',
                'category_id' => $categoryMap['DOCS'] ?? null,
                'description' => 'Formal corporate reports bound with plastic comb or wire spine and clear front cover.',
                'paper_type' => '80gsm Bright White Paper / Acetate Cover',
                'paper_size' => 'A4 (8.27 x 11.69 in)',
                'print_sides' => 'double_sided',
                'color_mode' => 'full_color',
                'turnaround_time' => '1-2 Business Days',
                'base_price' => 85.00,
                'min_quantity' => 2,
                'status' => 'active',
                'notes' => 'Clear PVC front cover and black leatherette back cover.',
                'sort_order' => 17,
            ],
            // 18. Worksheets
            [
                'name' => 'Educational & Training Worksheets',
                'item_code' => 'PRT-DOCS-0018',
                'category_id' => $categoryMap['DOCS'] ?? null,
                'description' => 'Bulk worksheet pads and training materials for schools, academies, and workshops.',
                'paper_type' => '70gsm Recycled Bond Paper',
                'paper_size' => 'A4 (8.27 x 11.69 in)',
                'print_sides' => 'single_sided',
                'color_mode' => 'monochrome',
                'turnaround_time' => 'Same Day Express',
                'base_price' => 2.50,
                'min_quantity' => 50,
                'status' => 'active',
                'notes' => 'Padded at top with chipboard backing.',
                'sort_order' => 18,
            ],
            // 19. Menus
            [
                'name' => 'Waterproof Laminated Dining Menus',
                'item_code' => 'PRT-MENU-0019',
                'category_id' => $categoryMap['MENU'] ?? null,
                'description' => 'Durable, wipeable restaurant and cafe menus with heavy thermal lamination sealed edges.',
                'paper_type' => '300gsm Synthetic Waterproof Cardstock',
                'paper_size' => 'A3 Folded to A4 Menu',
                'print_sides' => 'double_sided',
                'color_mode' => 'full_color',
                'turnaround_time' => '2-3 Business Days',
                'base_price' => 120.00,
                'min_quantity' => 5,
                'status' => 'active',
                'notes' => 'Spill-proof, grease-proof, and washable laminate.',
                'sort_order' => 19,
            ],
        ];

        foreach ($items as $item) {
            PrintItem::updateOrCreate(['item_code' => $item['item_code']], $item);
        }
    }
}
